react-phoenix/web/router.ex
defmodule Reddit.Router do
  use Reddit.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Reddit.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Reddit do
    pipe_through :browser # Use the default browser stack

    resources "/", PostController
  end

  scope "/auth", Reddit do
    pipe_through :browser

    get "/signout", SessionController, :signout
    get "/:provider", SessionController, :request
    get "/:provider/callback", SessionController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Reddit do
  #   pipe_through :api
  # end
end

react-phoenix/lib/reddit/endpoint.ex
defmodule Reddit.Endpoint do
  use Phoenix.Endpoint, otp_app: :reddit

  socket "/socket", Reddit.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :reddit, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_reddit_key",
    signing_salt: "dtbSiNgX"

  plug Reddit.Router
end

react-phoenix/lib/reddit/repo.ex
defmodule Reddit.Repo do
  use Ecto.Repo, otp_app: :reddit
end

react-phoenix/web/models/comment.ex
defmodule Reddit.Comment do
  use Reddit.Web, :model

  schema "comments" do
    field :content, :string
    belongs_to :user, Reddit.User
    belongs_to :post, Reddit.Post

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content])
  end
end

react-phoenix/web/models/post.ex
defmodule Reddit.Post do
  use Reddit.Web, :model

  schema "posts" do
    field :title, :string
    belongs_to :user, Reddit.User
    has_many :comments, Reddit.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end
end

react-phoenix/web/models/user.ex
defmodule Reddit.User do
  use Reddit.Web, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    has_many :posts, Reddit.Post

    timestamps()
  end

  def attrs_from_github(auth) do
    %{email: auth.info.email, token: auth.credentials.token, provider: "github"}
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end
end

react-phoenix/web/controllers/post_controller.ex
defmodule Reddit.PostController do
  use Reddit.Web, :controller
  alias Reddit.{Post}

  plug Reddit.Plugs.RequireAuth when action in [:new, :create]
  plug :check_post_owner when action in [:update, :edit, :delete]

  def index(conn, _params) do
    posts = Repo.all(Post)
    render conn, "index.html", posts: posts
  end

  def show(conn, %{"id" => post_id}) do
    post = Repo.get!(Post, post_id)
    render conn, "show.html", post: post
  end

  def new(conn, _params) do
    changeset = %Post{} |> Post.changeset(%{})

    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"post" => post}) do
    changeset = conn.assigns.user
      |> build_assoc(:posts)
      |> Post.changeset(post)

    case Repo.insert(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post Created")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => post_id}) do
    post = Repo.get(Post, post_id)
    changeset = post |> Post.changeset

    render conn, "edit.html", post: post, changeset: changeset
  end

  def update(conn, %{"post" => post, "id" => post_id}) do
    changeset = Repo.get(Post, post_id) |> Post.changeset(post)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post Updated")
        |> redirect(to: post_path(conn, :show, post))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset
    end
  end

  def delete(conn, %{"id" => post_id}) do
    Repo.get!(Post, post_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Post Deleted")
    |> redirect(to: post_path(conn, :index))
  end

  def check_post_owner(conn, _params) do
    %{params: %{"id" => post_id}} = conn

    case Repo.get(Post, post_id).user_id == conn.assigns.user.id do
      true ->
        conn
      false ->
        conn
        |> put_flash(:error, "You cannot edit that")
        |> redirect(to: post_path(conn, :index))
        |> halt()
    end
  end
end

react-phoenix/web/controllers/session_controller.ex
defmodule Reddit.SessionController do
  use Reddit.Web, :controller
  plug Ueberauth

  alias Reddit.User

  def callback(%{assigns: %{ ueberauth_failure: failure }}= conn, _params) do
    IO.inspect(failure)

    conn
    |> redirect(post_path(conn, :index))
  end

  def callback(%{assigns: %{ ueberauth_auth: auth }} = conn, %{"provider" => "github"}) do
    changeset = User.changeset(%User{}, User.attrs_from_github(auth))

    signin(conn, changeset)
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: post_path(conn, :index))
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome back")
        |> put_session(:user_id, user.id)
        |> redirect(to: post_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash("Error signing in", :error)
        |> redirect(to: post_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end
end

react-phoenix/web/views/comment_view.ex
defmodule Reddit.CommentView do
  use Reddit.Web, :view

  def render("comments.json", %{comment: comment}) do
    %{
      id: comment.id,
      content: comment.content
    }
  end
end

react-phoenix/web/views/error_view.ex
defmodule Reddit.ErrorView do
  use Reddit.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

react-phoenix/web/views/layout_view.ex
defmodule Reddit.LayoutView do
  use Reddit.Web, :view
end

react-phoenix/web/views/post_view.ex
defmodule Reddit.PostView do
  use Reddit.Web, :view
end

react-phoenix/web/templates/layout/_flash.html.eex
<div class="container">
  <%= if get_flash(@conn, :info) do %>
    <div class="card-panel teal lighten-2 white-text">
      <%= get_flash(@conn, :info) %>
    </div>
  <% end %>

  <%= if get_flash(@conn, :error) do %>
    <div class="card-panel red lighten-2 white-text">
      <%= get_flash(@conn, :error) %>
    </div>
  <% end %>
</div>

react-phoenix/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Reddit!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
    <script>
      <%= if @conn.assigns.user do %>
        window.redditToken = "<%= Phoenix.Token.sign(Reddit.Endpoint, "user_socket", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">Logo</a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Logout", to: session_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: session_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= render "_flash.html", conn: @conn %>

    <div class="section">
      <div class="container">
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

react-phoenix/web/templates/post/edit.html.eex
<%= form_for @changeset, post_path(@conn, :update, @post), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Post", class: "btn btn-primary" %>
<%= end %>

react-phoenix/web/templates/post/index.html.eex
<h2>Posts</h2>

<ul class="collection">
  <%= for post <- @posts do %>
    <li class="collection-item">
      <%= link post.title, to: post_path(@conn, :show, post) %>
      <%= if @conn.assigns.user.id == post.user_id do %>
        <div class="right">
          <%= link "Delete", to: post_path(@conn, :delete, post), method: :delete %>
          <%= link "Edit", to: post_path(@conn, :edit, post) %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <%= link to: post_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

react-phoenix/web/templates/post/new.html.eex
<%= form_for @changeset, post_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Create Post", class: "btn btn-primary" %>
<%= end %>

react-phoenix/web/templates/post/show.html.eex
<%= @post.title %>
<div id="target"></div>

<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    window.renderCommentsApp('target', <%= @post.id %>) 
  });
</script>